<a href="https://colab.research.google.com/github/7illz/Data-Structure/blob/main/MID_220.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NZF QUiz


In [ ]:
class Node:
  def __init__(self,elem,next = None):
    self.elem, self.next = elem,next

In [ ]:
def createList(arr):
  head = Node(arr[0])
  tail = head
  for i in range(1,len(arr)):
    newNode = Node(arr[i])
    tail.next = newNode
    tail = newNode
  return head

def printLinkedList(head):
  temp = head
  while temp != None:
    if temp.next != None:
      print(temp.elem, end = '-->')
    else:
      print(temp.elem)
    temp = temp.next
  print()

In [ ]:
arr=[7,85,54,16,11,30]
ar=[20,13,33,12]
head=createList(ar)
printLinkedList(head)
def strictly_greater(head):
    temp=head
    cur=head
    new=None
    while cur.next!=None:
        temp=cur.next
        while temp!=None:
            if cur.elem<temp.elem:
                if new==None:
                    new=Node(temp.elem,None)
                    var=new
                    break
                else:
                    n1=Node(temp.elem,None)
                    var.next=n1
                    var=n1
                    break
            temp=temp.next
        cur=cur.next
    return new



new_head=strictly_greater(head)
printLinkedList(new_head)


20-->13-->33-->12

33-->33



In [ ]:
class Stack:
    def __init__(self):
        self.top=None


    def push(self,val):
        new=Node(val,self.top)
        self.top=new

    def pop(self):
        if self.top==None:
            return None

        elem=self.top.elem
        self.top=self.top.next
        return elem

    def peek(self):
        if self.top==None:
            return None
        return self.top.elem

    def is_empty(self):
        if self.top==None:
            return True
        return False
def print_stack(st):
  if st.is_empty():
    return
  p = st.pop()
  print('|',p,end=' ')
  if p<10:
    print(' |')
  else:
    print('|')
  #print('------')
  print_stack(st)
  st.push(p)

In [ ]:
st=Stack()
st.push(23)
st.push(9)
st.push(17)
st.push(4)
print(st.peek())

4


In [ ]:
def modify_stack(st):
    new=Stack()
    while not st.is_empty():
        if st.top.next==None:
            store=st.pop()
            break
        var=st.pop()
        new.push(var)

    while not new.is_empty():
        temp=new.pop()
        st.push(temp)
    st.push(store)
    return st

var=modify_stack(st)
print_stack(var)




| 23 |
| 4  |
| 17 |
| 9  |


ARRAY


In [ ]:
import numpy as np

In [ ]:
def shiftLeft(arr):
    for i in range(len(arr)-1):
        arr[i]=arr[i+1]
    arr[len(arr)-1]=0
    print(arr)


arr=np.array([1,2,3,4])
shiftLeft(arr)

[2 3 4 0]


In [ ]:
def RotateLeft(arr):
    store=arr[0]
    for i in range(len(arr)-1):
        arr[i]=arr[i+1]
    arr[len(arr)-1]=store
    print(arr)

arr=np.array([1,2,3,4])
RotateLeft(arr)

[2 3 4 1]


In [ ]:
def RotateRight(arr):
    temp=arr[len(arr)-1]
    for i in range(len(arr)-1,-1,-1):
        arr[i]=arr[i-1]
    arr[0]=temp
    return arr


arr=np.array([1,2,3,4])
RotateRight(arr)

array([4, 1, 2, 3])

In [ ]:
def reverse(arr):
    v=0
    l=len(arr)
    for i in range(0,l//2,1):
        store=arr[i]
        arr[i]=arr[l-1-i]
        arr[l-1-i]=store
    print(arr)

arr=np.array([1,2,3,4])
reverse(arr)

[4 3 2 1]


**Instructions to Follow (Failing to follow these will result mark deductions).**


1.   You can not use any built-in function except len()
2.   You can not use any other python collections except array (e.g: tuptle, dictionaries etc.).
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.






In [ ]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

You will see the status Accepted after completion if your code is correct.

If your function is wrong you will see wrong[correction percentage]

Do not change the driver code statements. You can only change the input values to test your code.

In [ ]:
# Test 01: Play Right
def playRight(sequence, beats):
    for i in range(len(beats)):
        if beats[i]==1:
            var=RotateRight(sequence)
    return sequence




print("///  Test 01: Play Right  ///")
sequence = np.array([10, 20, 30, 40, 50, 60])
beats = np.array([1, 0, 0, 1, 0, 1])
returned_value = playRight(sequence, beats)
print(f'Task 1: {returned_value}')  # This should print [40, 50, 60, 10, 20, 30]

///  Test 01: Play Right  ///
Task 1: [40 50 60 10 20 30]


In [ ]:
# Test 02: Discard Cards
def discardCards(cards,number):
    new=np.array([0] * len(cards))
    j=0
    for i in range(len(cards)):
        if cards[i]!=number:
            new[j]=cards[i]
            j+=1
    return new


print("///  Test 02: Discard Cards  ///")
cards = np.array([1,2,3,2,8,2,2,5,7])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1, 3, 8, 5, 7, 0, 0, 0, 0]
unittest.output_test(returned_value, np.array([1, 3, 8, 5, 7, 0, 0, 0, 0]))

///  Test 02: Discard Cards  ///
Task 2: [1 3 8 5 7 0 0 0 0]
Accepted


In [ ]:
#Test 03: Merge Lineup
def mergeLineup(pokemon_1, pokemon_2):
  result =np.array([None]*len(pokemon_1)) #this array stores the resulting array
  for i in range(len(pokemon_1)):
    if pokemon_1[i]==None:
        pokemon_1[i]=0
    if pokemon_2[i]==None:
        pokemon_2[i]=0


  j=len(result)-1
  for i in range(len(pokemon_1)):
        result[i]= pokemon_1[i]+pokemon_2[j]
        j-=1
  return result




print("///  Test 03: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

///  Test 03: Merge Lineup  ///
Task 3: [12 3 28 -8 5]
Not Accepted [Your output: [12 3 28 -8 5]  |  Expected Output: [12  3 28 -8  5]]
Task 3: [4 17 6 27 2]
Not Accepted [Your output: [4 17 6 27 2]  |  Expected Output: [ 4 17  6 27  2]]


In [ ]:
# Test 04: Balance your Salami
def balanceSalami(salami):
    sum=0
    for i in range(len(salami)):
        sum+=salami[i]

    total=sum
    my=0
    sib=0
    for i in range(len(salami)-1):
        my+=salami[i]
        sib=total-my

        if my==sib:
            return True

    return False




print("///  Test 04: Balance Your Salami  ///")
salami = np.array([1, 1, 1, 2, 1])
returned_value = balanceSalami(salami)
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = [2, 1, 1, 2, 1]
returned_value = np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

salami = [10, 3, 1, 2, 10]
returned_value =  np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

///  Test 04: Balance Your Salami  ///
Task 4: True
Accepted
Task 4: False
Accepted
Task 4: True
Accepted


In [ ]:
# Test 05: Protecc Salami
def protectSalami(salami):
    traverse=[0] *len(salami)
    counter=[0] *len(salami)
    v=0
    x=0
    for i in range(len(salami)):
        if salami[i] not in traverse:
            traverse[v]=salami[i]
            v+=1
            count=0
            for j in range(i,len(salami)):
                if salami[i]==salami[j]:
                    count+=1
            if count in counter and count>1:
                return True

            counter[x]=count
            x+=1
    return False



print("///  Test 05: Protecc Salami  ///")
salami = np.array([4,5,6,6,4,3,6,4])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

///  Test 05: Protecc Salami  ///
Task 5: True
Accepted
Task 5: False
Accepted


BONUS TASK (Ungraded)

In [ ]:
# Test 06: Odd Even Wave
def waveYourFlag(arr):
  even=[0]*len(arr)
  odd=[0] *len(arr)
  temp=arr[0]
  result=np.array([0] *len(arr))
  j=0
  k=0

  for i in range(len(arr)):
       if arr[i]%2==0:
            even[j]=arr[i]
            j+=1
       else:
            odd[k]=arr[i]
            k+=1
  x=0
  y=0
  if temp%2==0:
        for i in range(len(arr)):
                if i%2==0:
                    result[i]=even[x]
                    x+=1
                else:
                    result[i]=odd[y]
                    y+=1
  else:
            for i in range(len(arr)):
                if i%2==1:
                    result[i]=even[x]
                    x+=1
                else:
                    result[i]=odd[y]
                    y+=1
  return result

print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,12,3,8,1,5])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

arr = np.array([45,23,78,84,41])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [45,78,23,84,41]
unittest.output_test(returned_value, np.array([45,78,23,84,41]))

///  Test 06: Odd Even Wave  ///
Task 6: [ 2  3 12  1  8  5]
Accepted
Task 6: [45 78 23 84 41]
Accepted


**Instructions to Follow (Failing to follow these will result mark penalties).**


1.   You can **NOT** use any built-in function except len()
2.   You can use the **shape** tuple of numpy arrays
2.   You can **NOT** use any other python collections (e.g: tuple, dictionaries etc.) except array.
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.zeros((10), dtype = int) #Initializing an array length 10 with values 0

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.







In [ ]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

In [ ]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))


#Zigzag Walk

In [ ]:
def walk_zigzag(floor):
    row=len(floor)
    col=len(floor[0])
    print(row)
    print(col)
    if row%2==0:
        for i in range(col):
            if i%2==0:
                for j in range(0,row,2):
                    print(floor[j][i], end=' ')
                print()
            else:
                for j in range(0,row,2):
                    print(floor[row-1-j][i], end = ' ')
                print()
    else:
        for i in range(col):
            if i%2==0:
                for j in range(0,row,2):
                    print(floor[j][i], end=' ')
                print()
            else:
                for j in range(row-2,-1,-2):
                    print(floor[j][i], end = ' ')
                print()






floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
|  1  |  4  |  2  |  8  |  6  |
-------------------------------
Walking Sequence:
5
5
3 9 1 
1 2 
4 7 2 
4 9 
1 8 6 
################
|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
Walking Sequence:
4
5
3 9 
1 2 
4 7 
4 9 
1 8 


#Wall Up Trost District

In [ ]:
def create_fence(district, depth):
    district_row, district_col = district.shape
    row=len(district) + (depth*2)
    col=len(district[0]) + depth *2
    mat=np.zeros((row,col), dtype =int)
    old=len(district)
    for i in range(row):
        for j in range(col):
            mat[i][j]=8
    print(mat)
    for i in range(depth,row-depth,1):
        for j in range(depth,col-depth,1):
            mat[i][j]=district[i-depth][j-depth]
    return mat


depth = 1
district = np.array([[2,3,4], [3,4,6], [2,1,4]])
print_matrix(district)
ans = create_fence(district, depth)
print_matrix(ans)
#This will print
# |  8  |  8  |  8  |  8  |  8  |
# -------------------------------
# |  8  |  2  |  3  |  4  |  8  |
# -------------------------------
# |  8  |  3  |  4  |  6  |  8  |
# -------------------------------
# |  8  |  2  |  1  |  4  |  8  |
# -------------------------------
# |  8  |  8  |  8  |  8  |  8  |
# -------------------------------
print('################')
depth = 2
district = np.array([
                 [2,3,4,1],
                 [3,4,6,5],
                 [2,1,4,7]
                ])
print_matrix(district)
ans = create_fence(district, depth)
print_matrix(ans)


|  2  |  3  |  4  |
-------------------
|  3  |  4  |  6  |
-------------------
|  2  |  1  |  4  |
-------------------
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]
|  8  |  8  |  8  |  8  |  8  |
-------------------------------
|  8  |  2  |  3  |  4  |  8  |
-------------------------------
|  8  |  3  |  4  |  6  |  8  |
-------------------------------
|  8  |  2  |  1  |  4  |  8  |
-------------------------------
|  8  |  8  |  8  |  8  |  8  |
-------------------------------
################
|  2  |  3  |  4  |  1  |
-------------------------
|  3  |  4  |  6  |  5  |
-------------------------
|  2  |  1  |  4  |  7  |
-------------------------
[[8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]]
|  8  |  8  |  8  |  8  |  8  |  8  |  8  |  8  |
-------------------------------------------------
|  8  |  8  |  8  |  8  |  8  |  8  |  8  |  8  |
-------------------------------------

#Crows vs Cats

In [ ]:
def strength_difference(clubroom):
  strength_diff = np.zeros(100, dtype = int)

  row=len(clubroom)
  size=((row*row)-row)//2
  arr=[0] * size
  x=0
  for i in range(row):
    diff=0
    for j in range(row):
        if i==j:
            pass
        if i<j:
            diff=clubroom[i][j]-clubroom[j][i]
            arr[x]=diff
            x+=1

  return np.array(arr)

clubroom = np.array([
[1,  2,  9,  7],
[4,  5,  1,  8],
[3,  6,  2,  7],
[2,  8,  6,  3]
])
print_matrix(clubroom)
returned_value = strength_difference(clubroom)
print('Strength Difference Array is : ', returned_value)
unittest.output_test(returned_value, np.array([-2, 6, 5, -5, 0, 1]))

|  1  |  2  |  9  |  7  |
-------------------------
|  4  |  5  |  1  |  8  |
-------------------------
|  3  |  6  |  2  |  7  |
-------------------------
|  2  |  8  |  6  |  3  |
-------------------------
Strength Difference Array is :  [-2  6  5 -5  0  1]
Accepted


#ATM's Triangle

In [ ]:
# def atm_triangle(n):
#   mat=np.zeros((n,n),dtype=int)
#   for i in range(n):
#     sum=0
#     for j in range(i+1):



#   return mat

# def print_without_none(matrix):
#   for i in range(len(matrix)):
#     for j in range(len(matrix)):
#         if matrix[i][j]!=0:
#             print((matrix[i][j]),end=' ')
#     print()

# n = 5
# returned_value = atm_triangle(n)
# print_without_none(returned_value)
#This should print
# 1
# 2  2
# 3  4  3
# 4  7  10  4
# 5  11 21  25  5

In [ ]:
# def rotate(mat):

# mat= np.array([[2,3,4], [3,4,6], [2,1,4]])

In [ ]:
###### 1
def rotate_right(head):
    temp=head
    cur=head
    while temp.next.next!=None:
        temp=temp.next
    var=temp.next
    temp.next=None
    var.next=head
    head=var

    return head




arr=np.array([1,2,3,4,5])
head=createList(arr)
ar=rotate_right(head)
printLinkedList(ar)

5-->1-->2-->3-->4



In [ ]:
#### 2
def new_list(head,head2):
    temp=head

    new=None
    while temp!=None:
        t=head2
        while t!=None:
            if temp.elem==t.elem:
                if new==None:
                    new=Node(temp.elem,None)
                    var=new
                    break
                else:
                    n1=Node(temp.elem,None)
                    var.next=n1
                    var=n1
                    break
            t=t.next
        temp=temp.next
    return new


arr=np.array([1,2,3,4,6])
ar=np.array([2,4,6,8])
head2=createList(ar)
head=createList(arr)
printLinkedList(head)
printLinkedList(head2)
call=new_list(head,head2)
printLinkedList(call)

1-->2-->3-->4-->6

2-->4-->6-->8

2-->4-->6



In [ ]:
def modify(head):
    new=None
    temp=head
    while temp!=None:
        if temp.elem%2==0:
            if new==None:
                new=Node(temp.elem,None)
                var=new
            else:
                even=Node(temp.elem,None)
                var.next=even
                var=even
        temp=temp.next
    temp=head
    while temp!=None:
        if temp.elem%2==1:
            odd=Node(temp.elem,None)
            var.next=odd
            var=odd
        temp=temp.next
    return new





arr=np.array([17,15,8,12,10,5,4,1,7,6])
head=createList(arr)
printLinkedList(head)
mod=modify(head)
printLinkedList(mod)

17-->15-->8-->12-->10-->5-->4-->1-->7-->6

8-->12-->10-->4-->6-->17-->15-->5-->1-->7



In [ ]:
def middle(head):
    fast=head
    slow=head
    while slow!=None and fast!=None and fast.next!=None:
        slow=slow.next
        fast=fast.next.next
    return slow.elem

ar=np.array([10,20,30,40,50])
arr=np.array([1,2,3,4,5,6])
head=createList(arr)
printLinkedList(head)
print(middle(head))

1-->2-->3-->4-->5-->6

4


In [ ]:
def loop(head):
    slow=head
    fast=head
    flag=False
    while slow!=None and fast!=None and fast.next!=None:
        slow=slow.next
        fast=fast.next.next
        if slow==fast:
            flag=True
            break
    return flag

a=Node(1,None)
b=Node(2,None)
c=Node(3,None)
d=Node(4,None)
e=Node(5,None)
a.next=b
b.next=c
c.next=d
d.next=e
e.next=b

print(loop(a))
arr=np.array([1,2,3,4,5,6])
head=createList(arr)
printLinkedList(head)
print(loop(head))

True
1-->2-->3-->4-->5-->6

False


In [ ]:
#### 10
def delete(head):
    temp=head
    while temp.next!=None:
        temp.next=temp.next.next
        temp=temp.next
    return head
baal=np.array([10,20,30,40,50])
head=createList(baal)
printLinkedList(head)
call=delete(head)
printLinkedList(call)

10-->20-->30-->40-->50

10-->30-->50



**INSTRUCTIONS FOR STUDENTS:**

*   YOU CANNOT USE ANY BUILT-IN FUNCTION EXCEPT len() IN PYTHON. [negative indexing, append is prohibited]
*   YOUR CODE SHOULD WORK FOR ANY 2D ARRAYS.
*   YOU CANNOT USE ANY OTHER PYTHON COLLECTIONS EXCEPT NUMPY ARRAY (TUPLE, DICTIONARIES ETC. NOT ALLOWED)
*   CREATE A COPY OF THIS IPYNB FILE IN YOUR DRIVE FIRST AS CHANGES IN THE GIVEN IPYNB FILE WILL NOT BE SAVED.

In [ ]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  print('-'*(col*6)+'-')
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))

**Game Arena**

In [ ]:
import numpy as np

#Do not change the return statement or the parameters of the gainPoints function..
def check(arr,i,j,count):
    r=len(arr)
    c=len(arr[0])
    if i-1 < 0:
        pass
    else:
        if arr[i-1][j]==2:
            count+=1
    if i+1 >= r:
        pass
    else:
        if arr[i+1][j]==2:
            count+=1
    if j+1 >=c:
        pass
    else:
        if arr[i][j+1]==2:
            count+=1
    if j-1 <0:
        pass
    else:
        if arr[i][j-1]==2:
            count+=1
    return count

def gainPoints(arr):
    r,c=arr.shape
    count=0
    var=0
    for i in range(r):
        for j in range(c):
            if arr[i][j]%50==0 and arr[i][j]>0:
                call=check(arr,i,j,count)
                var+=call
    gained_point=var*2
    return gained_point


#DRIVER CODE
#DO NOT CHANGE THE CODE BELOW

print("=============== Game 1 ===============")
game_arena = np.array([[0, 2, 2, 0],
                      [50, 1, 2, 0],
                      [2, 2, 2, 0],
                      [1, 100, 2, 0]])

print_matrix(game_arena)
points = gainPoints(game_arena)                                 #should return 6
if points>=10:
  print(f'Points Gained: {points}. Your team has survived the game.')
else:
  print(f'Points Gained: {points}. Your team is out.')

print()
print("=============== Game 2 ===============")
game_arena = np.array([[0, 2, 2, 0, 2],
                        [1, 50, 2, 1, 100],
                        [2, 2, 2, 0, 2],
                        [0, 200, 2, 0, 0]])

print_matrix(game_arena)
points = gainPoints(game_arena)                                 #should return 14
if points>=10:
  print(f'Points Gained: {points}. Your team has survived the game.')
else:
  print(f'Points Gained: {points}. Your team is out.')

=============== Game 1 ===============
-------------------------
|  0  |  2  |  2  |  0  |
-------------------------
|  50 |  1  |  2  |  0  |
-------------------------
|  2  |  2  |  2  |  0  |
-------------------------
|  1  |  100 |  2  |  0  |
-------------------------
Points Gained: 6. Your team is out.

=============== Game 2 ===============
-------------------------------
|  0  |  2  |  2  |  0  |  2  |
-------------------------------
|  1  |  50 |  2  |  1  |  100 |
-------------------------------
|  2  |  2  |  2  |  0  |  2  |
-------------------------------
|  0  |  200 |  2  |  0  |  0  |
-------------------------------
Points Gained: 14. Your team has survived the game.


In [ ]:
def flip_vertical(mat):
    r,c=mat.shape
    new=np.zeros((r,c),dtype=int)
    for i in range(r):
        for j in range(c):
            new[i][j]=mat[i][c-1-j]

    return new


#Driver Code
#DO NOT CHANGE ANYTHING BELOW
print("=======TEST 1=======")
m = np.random.randint(15,size=(4,3)) #This creates an np array of 4 x 3 where the values are random numbers from [0,15) range
print_matrix(m)
print()
print_matrix(flip_vertical(m))
print()

print("=========TEST 2=========")
m = np.random.randint(15,size=(5,5)) #This creates an np array of 5 x 4 where the values are random numbers from [0,15) range
print_matrix(m)
print()
print_matrix(flip_vertical(m))

=======TEST 1=======
-------------------
|  13 |  10 |  13 |
-------------------
|  7  |  13 |  12 |
-------------------
|  9  |  3  |  9  |
-------------------
|  0  |  0  |  6  |
-------------------

-------------------
|  13 |  10 |  13 |
-------------------
|  12 |  13 |  7  |
-------------------
|  9  |  3  |  9  |
-------------------
|  6  |  0  |  0  |
-------------------

=========TEST 2=========
-------------------------------
|  0  |  6  |  12 |  12 |  13 |
-------------------------------
|  6  |  4  |  2  |  2  |  7  |
-------------------------------
|  0  |  0  |  13 |  7  |  10 |
-------------------------------
|  13 |  5  |  1  |  14 |  5  |
-------------------------------
|  10 |  0  |  4  |  7  |  8  |
-------------------------------

-------------------------------
|  13 |  12 |  12 |  6  |  0  |
-------------------------------
|  7  |  2  |  2  |  4  |  6  |
-------------------------------
|  10 |  7  |  13 |  0  |  0  |
-------------------------------
|  5  |  14 |  

In [ ]:
def secondary(m):
    r,c=m.shape
    sum=0
    for i in range(r):
        for j in range(r-1-i,-1,-1):
            sum+=m[i][j]
            print(sum)
            break
    print(sum)
    return sum


#Driver Code
#DO NOT CHANGE ANYTHING BELOW
print("=======TEST 1=======")
m = np.random.randint(15,size=(3,3)) #This creates an np array of 4 x 3 where the values are random numbers from [0,15) range
print_matrix(m)
print()
print_matrix(flip_vertical(m))
print()

print("=========TEST 2=========")
m = np.random.randint(15,size=(5,5)) #This creates an np array of 5 x 4 where the values are random numbers from [0,15) range
print_matrix(m)
print()
print_matrix(flip_vertical(m))

=======TEST 1=======
-------------------
|  11 |  8  |  10 |
-------------------
|  13 |  9  |  13 |
-------------------
|  0  |  14 |  4  |
-------------------

-------------------
|  10 |  8  |  11 |
-------------------
|  13 |  9  |  13 |
-------------------
|  4  |  14 |  0  |
-------------------

=========TEST 2=========
-------------------------------
|  12 |  12 |  11 |  8  |  13 |
-------------------------------
|  13 |  13 |  12 |  9  |  11 |
-------------------------------
|  9  |  6  |  12 |  10 |  3  |
-------------------------------
|  13 |  2  |  8  |  3  |  1  |
-------------------------------
|  0  |  6  |  13 |  0  |  7  |
-------------------------------

-------------------------------
|  13 |  8  |  11 |  12 |  12 |
-------------------------------
|  11 |  9  |  12 |  13 |  13 |
-------------------------------
|  3  |  10 |  12 |  6  |  9  |
-------------------------------
|  1  |  3  |  8  |  2  |  13 |
-------------------------------
|  7  |  0  |  13 |  6  |  0  |

In [ ]:
mat = np.array([[2, 7, 5, 10], [9, 3, 8, 4]])
def find(mat):
    row=len(mat)
    col=(len(mat[0]))
    arr=[0]*row
    for i in range(row):
        max=mat[i][0]
        for j in range(col):
            if mat[i][j]>max:
                max=mat[i][j]
        arr[i]=max
    min=arr[0]
    print(arr)
    for i in range(len(arr)):
        if arr[i]<min:
            min=arr[i]

    print('min value is',min)

find(mat)


[10, 9]
min value is 9


In [ ]:
mat = np.array([[4, 3, 8, -7], [2, 5, -1, 12],[7,16,9,10 ],[4,13,11,18]])
def secondary(m):
    r=len(m)
    sum=0
    for i in range(r):
        for j in range(r-1-i,-1,-1):
            sum+=m[i][j]
            # print(sum)
            break
    print(sum)
call=secondary(mat)
# print_matrix(call)

12


In [ ]:
s=Stack()
s.push(35)
s.push(25)
s.push(15)
s.push(5)
s.push(20)
s.push(10)
s.peek()


def remove_middle(s):
    count=0
    new=Stack()
    while not  s.is_empty():
        emp=s.pop()
        new.push(emp)
        count+=1
    mid=count//2
    nc=0
    print(count)
    while not new.is_empty():
        if mid==nc:
            new.pop()
        temp=new.pop()
        s.push(temp)
        nc+=1
    return s

print_stack(s)
call=remove_middle(s)
print()
print_stack(call)


| 10 |
| 20 |
| 5  |
| 15 |
| 25 |
| 35 |
6

| 10 |
| 20 |
| 15 |
| 25 |
| 35 |


MID SPRING



In [ ]:
arr=[4,5,6,6,4,3,6,4]
arrr=[3,4,6,3,4,7,4,6,8,6,6]
